version: '3.7'
services:
   server:
      build:
         context: .
         dockerfile: Dockerfile
      image: rmp-server
      ports:
         - 5000:5000
      deploy:
         mode: replicated
         replicas: 1
         restart_policy:
            condition: on-failure
